### ISSUE TITLE
steam-acolyte is currently dead

### ISSUE THREAD

**Issue by AndrewBraunEE** [coldfix/steam-acolyte#10]
Waiting for steam to exit.
Traceback (most recent call last):
  File "<decorator d:\program files\python3.6\lib\site-packages\steam_acolyte\window.py>", line 1, in <lambda>
  File "d:\program files\python3.6\lib\site-packages\steam_acolyte\util.py", line 85, in wrapper
    return fn(obj, *args, **kwargs)
  File "d:\program files\python3.6\lib\site-packages\steam_acolyte\window.py", line 84, in _on_locked
    self.steam.store_login_cookie()
  File "<decorator d:\program files\python3.6\lib\site-packages\steam_acolyte\steam.py>", line 1, in <lambda>
  File "d:\program files\python3.6\lib\site-packages\steam_acolyte\util.py", line 85, in wrapper
    return fn(obj, *args, **kwargs)
  File "d:\program files\python3.6\lib\site-packages\steam_acolyte\steam.py", line 203, in store_login_cookie
    config, r'InstallConfigStore\Software\Valve\Steam\Accounts')
  File "d:\program files\python3.6\lib\site-packages\steam_acolyte\util.py", line 62, in subkey_lookup
    d = ld[entry]
KeyError: 'Valve'

**Comment by AndrewBraunEE** [comment]
Actually, I take it back. This error only appears when you haven't logged into the account before running SteamAcolyte. Doh!

**Comment by coldfix** [comment]
Oh, ok, thanks, I'll take a look.

So the scenario is that steam already knows the user but you haven't logged into it?
